In [1]:
import pandas as pd
import shutil

# Read

In [3]:
via_meta = pd.read_excel(r"path_to\VIA Cases Meta data.xlsx" )

via_meta = via_meta[["CaseNumber", "CaseID", "VIA"]]
via_meta.head(2)

   CaseNumber CaseID       VIA
0           1    AFC  Negative
1           2    AJL  Negative

In [4]:
via_image_dat = pd.read_excel(r"path_to\Cases - Images.xlsx")
via_image_dat= via_image_dat[["CaseNumber", "File", "Type"]]
via_image_dat.head(2)

   CaseNumber      File                               Type
0           1  AFC0.jpg  Before application of acetic acid
1           1  AFC1.jpg   After application of acetic acid

In [5]:
def find_matches(row, df2):
    matches = df2[df2['File'].str.startswith(row['CaseID'])]
    return matches

In [6]:
results = []

for _, row in via_meta.iterrows():
    matches = find_matches(row, via_image_dat)
    for _, match in matches.iterrows():
        print("FALSE:" + str(row['CaseNumber'] ) if row['CaseNumber'] != match['CaseNumber'] else "", end = "")
        results.append({
            'File': match['File'],
            'CaseID': row['CaseID'],
            'CaseNumber': row['CaseNumber'],
            'Type': match['Type'],
            'Class': row['VIA']
        })

final_via_set = pd.DataFrame(results)

In [7]:
final_via_set.head()

       File CaseID  CaseNumber                               Type     Class
0  AFC0.jpg    AFC           1  Before application of acetic acid  Negative
1  AFC1.jpg    AFC           1   After application of acetic acid  Negative
2  AJL0.jpg    AJL           2  Before application of acetic acid  Negative
3  AJL1.jpg    AJL           2   After application of acetic acid  Negative
4  AGY0.jpg    AGY           3  Before application of acetic acid  Negative

In [8]:
final_via_set['Class'].value_counts()

Class
Positive                193
Negative                187
Suspicious of cancer     40
Name: count, dtype: int64

In [9]:
final_via_set[final_via_set["CaseNumber"] == 166]

,File,CaseID,CaseNumber,Type,Class
377,APW1.jpg,APW,166,Before application of acetic acid,Positive
378,APW2.jpg,APW,166,After application of acetic acid,Positive
379,APW3.jpg,APW,166,After application of Lugol’s iodine,Positive

# Move data

In [10]:
def copy_images(from_to):
    c = 0
    for fr, to in from_to:
        try:
            shutil.copy(fr, to)
        except:
            print("ERROR:", fr, to)
        c +=1
        print(c, "done")

In [11]:
BASE_PATH_FROM = r"path_to\VIA"
BASE_PATH_TO = r"path_to_folders"

## Manage special cases first

In [12]:
ABNORMAL_CLASSES  = [i for i in via_meta["VIA"].unique() if any(w in i.lower() for w in ["positive", "cancer"])]
ABNORMAL_CLASSES

['Positive', 'Suspicious of cancer']

In [ ]:
# generate image list for Cancer folder
abnormal_path_to = BASE_PATH_TO + "\\Abnormal\\"
abnormal_from_to = []
for class_ in ABNORMAL_CLASSES:
    rows = final_via_set[final_via_set['Class'] == class_]
    paths = [
        ( BASE_PATH_FROM + "\\Case {:03}\\{}".format(
            row["CaseNumber"],
            row["File"]
            ),
          abnormal_path_to + row['File'])
            for _, row in rows.iterrows()]
    abnormal_from_to.extend(paths)
abnormal_from_to[:2]

In [14]:
copy_images(abnormal_from_to)

1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 done
66 done
67 done
68 done
69 done
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
102 done
103 done
104 done
105 done
106 done
107 done
108 done
109 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
120 done
121 done
122 done
123 done
124 done
125 done
126 done
127 done
128 done
129 done
130 done
131 done
132 done
133 done
134 done
135 done
136 done
137 done
138 done
139 done
140 done
141 done
142 done
143 done
144 done
145 done
146 done
147 done
148 done
149 done
150 done
151 done
152 done
153 done
154 done
155 done
156 done
157 done
158 done
159 done
160 done
161 done
162 done
163 done
164 done
165 done
166 done
167 done
168 done
169 done
170 done
171 done
172 done
173 done
174 done
175 done
176 done
177 done
178 done
179 done
180 done
181 done
182 done
183 done
184 done
185 done
186 done
187 done
188 done
189 done
190 done
ERROR: C:\Users\taral\OneDrive\Documents\Major project\Data\IARC\VIA\Case 166\APW1.jpg C:\Users\taral\OneDrive\Documents\Major project\Data\DEEPTEST\Abnormal\APW1.jpg
191 done
ERROR: C:\Users\taral\OneDrive\Documents\Major project\Data\IARC\VIA\Case 166\APW2.jpg C:\Users\taral\OneDrive\Documents\Major project\Data\DEEPTEST\Abnormal\APW2.jpg
192 done
ERROR: C:\Users\taral\OneDrive\Documents\Major project\Data\IARC\VIA\Case 166\APW3.jpg C:\Users\taral\OneDrive\Documents\Major project\Data\DEEPTEST\Abnormal\APW3.jpg
193 done
194 done
195 done
196 done
197 done
198 done
199 done
200 done
201 done
202 done
203 done
204 done
205 done
206 done
207 done
208 done
209 done
210 done
211 done
212 done
213 done
214 done
215 done
216 done
217 done
218 done
219 done
220 done
221 done
222 done
223 done
224 done
225 done
226 done
227 done
228 done
229 done
230 done
231 done
232 done
233 done

## Move rest of images

In [15]:
NORMAL_CLASSES = ["Negative"]

In [ ]:
all_from_to = list()
for class_ in NORMAL_CLASSES:
    rows = final_via_set[final_via_set['Class'] == class_]
    paths = [
        ( BASE_PATH_FROM + "\\Case {:03}\\{}".format(
            row["CaseNumber"],
            row["File"]
            ),
          BASE_PATH_TO + "\\Normal\\" + row['File'])
            for _, row in rows.iterrows()]
    all_from_to.extend(paths)
all_from_to[:2]

In [17]:
copy_images(all_from_to)

1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 done
66 done
67 done
68 done
69 done
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
102 done
103 done
104 done
105 done
106 done
107 done
108 done
109 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
120 done
121 done
122 done
123 done
124 done
125 done
126 done
127 done
128 done
129 done
130 done
131 done
132 done
133 done
134 done
135 done
136 done
137 done
138 done
139 done
140 done
141 done
142 done
143 done
144 done
145 done
146 done
147 done
148 done
149 done
150 done
151 done
152 done
153 done
154 done
155 done
156 done
157 done
158 done
159 done
160 done
161 done
162 done
163 done
164 done
165 done
166 done
167 done
168 done
169 done
170 done
171 done
172 done
173 done
174 done
175 done
176 done
177 done
178 done
179 done
180 done
181 done
182 done
183 done
184 done
185 done
186 done
187 done